# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

language: python
os: linux
jobs:
  include:
    - name: Py3.6
      python: 3.6
      dist: bionic
    - name: Py3.7
      python: 3.7
      dist: focal
    - name: Py3.8
      python: 3.8
      dist: focal
    - name: Py2.7 (legacy)
      python: 2.7
      dist: xenial
cache: pip
env:
  - MPLBACKEND=module://matplotlib.backends.backend_agg
addons:
  apt:
    packages:
      - openjdk-8-jre-headless
      - ant

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - support/rat.sh download
  # Bring pip up to date
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMan.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/PACMAN.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/DataSpecification.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/spalloc.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/sPyNNaker.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/IntroLab.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/PyNN8Examples.git

install:
  - pip install -r requirements-test.txt
  - pip install 'pylint<2.5' python-coveralls 'coverage>=4.4,<5.0'
  - python ./setup.py install

before_script:
  - echo '[Machine]' > ~/.spynnaker.cfg
  - echo "machineName = $SPINNAKER_BOARD_ADDRESS" >> ~/.spynnaker.cfg
  - echo "version = ${SPINNAKER_BOARD_VERSION:-5}" >> ~/.spynnaker.cfg
  - echo '[Database]' >> ~/.spynnaker.cfg
  - echo '[Simulation]' >> ~/.spynnaker.cfg
  - echo '[Buffers]' >> ~/.spynnaker.cfg

script:
  # Tests
  - py.test --cov-report= unittests --cov spynnaker8
  # Code quality checks
  - flake8 spynnaker8 unittests p8_integration_tests
  - ( pylint --output-format=colorized --disable=R,C spynnaker8; exit $(($? & 35)) )
  # Copyright check
  - support/rat.sh run
  # Doc check
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - COVERALLS_PARALLEL=true coveralls
