language: python
python:
  - 2.7
  - 3.6
dist: trusty

cache: pip

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  # Bring pip up to date
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMan.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/PACMAN.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/DataSpecification.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/spalloc.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/sPyNNaker.git

install:
  - pip install -r requirements-test.txt
  - pip install python-coveralls 'coverage>=4.4'
  - python ./setup.py install

before_script:
  - echo '[Machine]' > ~/.spynnaker.cfg
  - echo "machineName = $SPINNAKER_BOARD_ADDRESS" >> ~/.spynnaker.cfg
  - echo "version = ${SPINNAKER_BOARD_VERSION:-5}" >> ~/.spynnaker.cfg
  - echo '[Database]' >> ~/.spynnaker.cfg
  - echo '[Simulation]' >> ~/.spynnaker.cfg
  - echo '[Buffers]' >> ~/.spynnaker.cfg

script:
  # Tests
  - py.test unittests --cov spynnaker8
  # Code quality check
  - flake8 spynnaker8 unittests p8_fga_tests p8_integration_tests
  # Doc check
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
